### ISSUE TITLE
Feature request for option to stick to Gorilla Context

### ISSUE THREAD

**Issue by andyhaskell** [gorilla/mux#237] opened 2017-03-02 15:07 UTC
Recently I was using Gorilla Mux in a deployed App Engine app and got the panic in `appengine.NewContext`:

`NewContext passed an unknown http.Request`

When I pinned my Gorilla Mux dependency to the version immediately before the logic was added for Go 1.7+ to use `request.WithContext` rather than a Gorilla context, though, I didn't get the panic. Looking at the source code for `http.Request.NewContext`, that function returns a pointer to a completely new `http.Request`, so I think the issue was that that request was not known to App Engine since it's a fresh pointer.

Because of this, I would like to send a feature request for a `Router` to have a `WithGorillaContext()` method that would override the default Mux behavior that in Go 1.7+ we use `Request.WithContext` if it's set to true.

**Comment by elithrar** [comment] 2017-03-02 15:18
The problem is that any use of gorilla/context in Go 1.7 - where
Request.Context() could exist in any part of the application - does not
work.

Can you show the application code where this problem occurred? Go must do a
shallow copy of the Request which is why the address changes.

**Comment by AndyHaskell** [comment] 2017-03-02 16:15
Here's the stack trace:

```
google.golang.org/appengine/panic(0xc96560, 0xc420339ee0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
log.Panic(0xc4206c9628, 0x1, 0x1)
	/usr/local/go/src/log/log.go:322 +0xc0
google.golang.org/appengine/internal.WithContext(0x7fac6a3e3070, 0xc4200103f0, 0xc420317600, 0x0, 0x7fac6a3e3070)
	/go/src/app/_gopath/src/google.golang.org/appengine/internal/api.go:268 +0x17f
google.golang.org/appengine.WithContext(0x7fac6a3e3070, 0xc4200103f0, 0xc420317600, 0x7fac6a3e3070, 0xc4200103f0)
	/go/src/app/_gopath/src/google.golang.org/appengine/appengine.go:73 +0x3f
google.golang.org/appengine.NewContext(0xc420317600, 0x3, 0xc42001a050)
.
.
.
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420294960, 0x12bc740, 0xc420b1ca80, 0xc420317600)
	/go/src/app/_gopath/src/github.com/gorilla/mux/mux.go:114 +0x10c
net/http.(*ServeMux).ServeHTTP(0x12f77c0, 0x12bc740, 0xc420b1ca80, 0xc4208d7900)
	/usr/local/go/src/net/http/server.go:2238 +0x130
google.golang.org/appengine/internal.executeRequestSafely(0xc420b1ca80, 0xc4208d7900)
	/go/src/app/_gopath/src/google.golang.org/appengine/internal/api.go:156 +0x77
google.golang.org/appengine/internal.handleHTTP(0x12beac0, 0xc4203f81c0, 0xc4208d7900)```

I saw that `Request.WithContext` creates a fresh HTTP request when it's called from `setVars` and `setCurrentRoute`, so as you said, that is where we get a request with a new address. The simplest way I can think of for keeping access to the original `Request` would be a `setOriginalRequest` method storing the original request pointer in the context, but that feels kinda unidiomatic and unintuitive to me to have to retrieve an otherwise-identical copy of the same request from a `Context` just to be able to use it as an App Engine request.

**Comment by cnbuff410** [comment] 2017-03-07 06:05
I'm having this issue as well on appengine managed VM. Ever since the VM starts using Go 1.8, all requests going through mux break.

@AndyHaskell , how do you pin the mux dependency? Did you manually download that specific version and overwrite the one on your disk?

**Comment by AndyHaskell** [comment] 2017-03-10 16:20
I use Glide so I did
```yaml
- package: github.com/gorilla/mux
  version: [the commit before Go 1.7 came out]
```

**Comment by AndyHaskell** [comment] 2017-03-10 16:21
@cnbuff410  I use Glide so I did
```yaml
- package: github.com/gorilla/mux
  version: [the commit before Go 1.7 came out]
```

**Comment by warent** [comment] 2017-06-02 03:30
This bug is really unfortunate. Spent way too much time trying to isolate it back here.
Also for some reason even pinning the version back to an old version of mux doesn't fix it for me. The only solution is to remove gorilla/mux entirely in my case

**Comment by elithrar** [comment] 2017-06-02 05:04
If you are running an older mux with newer middleware, or newer middleware
with an older mux, there is no practical way to avoid this.

What version of mux were you on?

**Comment by cnbuff410** [comment] 2017-06-07 18:17
For now I'm still using the commit before Go 1.7 came out and everything still works so far. Once I upgrade things will break

**Comment by elithrar** [comment] 2017-09-19 12:59
Closing this as wontfix ("cannotfix").

**Closed by elithrar** 2017-09-19 12:59 UTC
