### ISSUE TITLE
URL Encoded Parameters Still Not Working in Go 1.5.1

### ISSUE THREAD

**Issue by derekdowling** [gorilla/mux#132] opened 2015-11-06 01:35 UTC
So as a follow up to #77, I'm running Go 1.5.1 which claims to have been the cause of that issue: https://github.com/gorilla/mux/issues/77#issuecomment-101772763 and I am still seeing issues with uriEncoded paths.

Example:
```go
    // router build
	router = mux.NewRouter()
	router.HandleFunc("/status", status).Methods("GET")

	apiRouter := mux.NewRouter()
	apiRouter.HandleFunc("/foo", getFooList).Methods("GET")
	apiRouter.HandleFunc("/foo/{bar}", getFoo).Methods("GET")

	router.PathPrefix("/foo").Handler(apiRouter)

    url := httptest.NewServer(router).URL
    url1 := strings.Join([]string{url, "/foo/bar%2ftest"}, "")
    // url2 := strings.Join([]string{url, "/foo/bar.test}", "")

	req, _ := http.NewRequest("GET", url1, nil)

	client := &http.Client{}
	req, err := client.Do(req)
    fmt.Printf("Req: %+v \n Err: %+v \n", req, err)
```

If I use `url1` I get a 404, if I use `url2` I get a 200. Thoughts? I am using Ember-Data to generate API calls so short of performing a huge hack on both ends which doesn't seem reasonable.

**Comment by garyburd** [comment] 2015-11-06 08:09
The problem is that the mux matches the fully decoded path in req.URL.Path.  This issue can be fixed by changing the mux to match  [req.RequestURI](https://godoc.org/net/http#Request.RequestURI) or [req.URL.RawPath](https://godoc.org/net/url#URL.RawPath) , but that change might break existing applications.  RequestURI has been available since Go 1.  RawPath was added on 1.5.

A workaround is to change the pattern to:

         apiRouter.HandleFunc("/foo/{bar:.*}", getFoo).Methods("GET")

This pattern matches "/foo/bar%2ftest" and "/foo/bar/test". If you don't want "/foo/bar/test" to match, the modify the handler to check [req.RequestURI](https://godoc.org/net/http#Request.RequestURI) or the [req.URL.RawPath](https://godoc.org/net/url#URL.RawPath) and return status 404 as appropriate.

**Comment by derekdowling** [comment] 2015-11-06 18:00
Okay, while this isn't exactly ideal, it should at least work. How then would I handle:
`apiRouter.HandleFunc("/foo/{bar%2ftest}/{baz}", getFoo).Methods("GET")`?

**Comment by derekdowling** [comment] 2015-11-06 18:22
Well, `/foo/{bar:.*}/{baz}` seems to work as expected! @garyburd thanks for the speedy response and getting me unstuck! I still think that this is a bug as it's definitely not the expected functionality and I spent a considerable amount of time trying to pinpoint what was wrong with my routing.

**Comment by vaikas-google** [comment] 2015-11-24 23:48
I am also running into this (last issue in this thread) and have made the following unit tests and changes to use EscapedPath() instead of Path directly and it now works great for my needs. Is this something that might be considered for a pull request?
https://github.com/gorilla/mux/compare/master...vaikas-google:master

**Comment by elithrar** [comment] 2015-11-25 00:00
Note that using the `EscapedPath()` method would require us to drop support for all versions of Go prior to 1.5. I don't think we're ready to do that just yet.

The alternative would be to implement our own function that takes a `*url.URL` and performs the same logic, with the maintenance overhead that goes along with such an approach.

**Comment by vaikas-google** [comment] 2015-11-25 00:04
Thanks much!

Aha, I was not aware of that :) Seems like a solid reason. I can try to
take a crack at implementing a method like that if it seems like a viable
approach?

Also, I currently return the encoded variable, it's probably better to
return the decoded one, but thoughts on that?

**Comment by duglin** [comment] 2015-11-25 11:51
Would using URL.RawPath instead of URL.Path at this line: https://github.com/gorilla/mux/blob/master/mux.go#L71  be an option?  I guess if support for pre-Go 1.5 is required then probably not.

It was mentioned that using RequestURI might break existing apps, but couldn't treating %2F as / be considered a bug and therefore the change in behavior needed/expected?

We're running into a similar issue: https://github.com/docker/docker/pull/16577

**Comment by duglin** [comment] 2015-11-25 11:54
Ah, never mind about RawPath - I see that EscapedPath() is the proper was to get the same info.

**Comment by duglin** [comment] 2016-03-12 20:49
@elithrar is this now fixed?

**Comment by elithrar** [comment] 2016-03-12 20:52
No - I'm open to a PR, but as this has been quiet I'd intepreted the feature wasn't required. I'm not entirely convinced it's a "bug".

The fix is: either break compat for all users pre Go-1.5 (not an option) or add in logic to handle that ourselves.

**Comment by duglin** [comment] 2016-03-12 20:58
@vaikas-google were you going to submit a PR?

**Comment by chrisdostert** [comment] 2016-03-28 18:35
+1. I'm also in need of this

**Comment by chrisdostert** [comment] 2016-03-28 20:12
@elithrar in re: "I'm not entirely convinced it's a bug"
throwing the rfc @ you in hopes of buy in ; ) 

see [rfc3986#section-2.2](https://tools.ietf.org/html/rfc3986#section-2.2)
"When a URI is dereferenced, the components and subcomponents
   significant to the scheme-specific dereferencing process (if any)
   must be parsed and separated before the percent-encoded octets within
   those components can be safely decoded, as otherwise the data may be
   mistaken for component delimiters."

**Comment by elithrar** [comment] 2016-03-28 20:24
@chrisdostert Alright—that's all I needed. Are you able to submit a PR? Happy to work with you on it/review, but I don't have time to fix this any time in the near future.

Any fix must be backwards compat.

**Comment by hsinhoyeh** [comment] 2016-06-07 09:29
hey guys, do we have any update here? I also hit into this.

**Comment by elithrar** [comment] 2016-06-07 13:14
Open to any pull requests to fix this.

**Comment by kushmansingh** [comment] 2016-08-16 15:21
#184 created, does not break backwards compatibility.

**Comment by kushmansingh** [comment] 2016-08-25 15:15
#184 merged. This issue can be closed?

**Comment by kushmansingh** [comment] 2016-09-02 19:23
#190 also merged. @elithrar, issue resolved?

**Comment by elithrar** [comment] 2016-09-04 02:11
Done.

**Closed by elithrar** 2016-09-04 02:11 UTC
Labels: bug
