### ISSUE TITLE
mux package doesn't work 

### ISSUE THREAD

**Issue by imjmakki** [gorilla/mux#670] opened 2022-02-16 14:37 UTC
no required module provides package github.com/gorilla/mux: go.mod file not found in current directory or any parent directory; see 'go help modules'

It's keep giving me that even after I installed the package

**Comment by ya5u** [comment] 2022-02-18 14:24
@imjmakki Please follow the issue template and describe in detail your environment and the steps to reproduce it.

And I'm guessing that it's not a bug, but a problem with your Go environment.

**Comment by oswinfox** [comment] 2022-02-22 18:16
Hello, I have the same issue and behaviour as @imjmakki: 

**Describe the bug**

Issue is that after installing mux package as follow: 

`go get github.com/gorilla/mux`

Nothing is happening and then when adding mux in my main.go file as follow: 

```
import (
        "github.com/gorilla/mux"
)
```

I go error when doing `go run main.go`: 

main.go:13:9: no required module provides package github.com/gorilla/mux: go.mod file not found in current directory or any parent directory; see 'go help modules'

Module did not installed well with `go get`.

**Versions**
> Go version: `go1.17.5 linux/amd64`
> package version: run `git rev-parse HEAD` inside the repo

Cannot do this because mux is not well installed. 


**Steps to Reproduce**
> How can the bug be triggered?

Create a new test project in: `$GOPATH/src`

as follow: 

mkdir -p $GOPATH/src/testproject

Add a new main.go with the following: 

```
// This is the name of our package
// Everything with this package name can see everything
// else inside the same package, regardless of the file they are in
package main

// These are the libraries we are going to use
// Both "fmt" and "net" are part of the Go standard library
import (
	// "fmt" has methods for formatted I/O operations (like printing to the console)
	"fmt"
	// The "net/http" library has methods to implement HTTP clients and servers
	"net/http"
        "github.com/gorilla/mux"
)

func main() {
        // Declare a new router
	r := mux.NewRouter()

	// This is where the router is useful, it allows us to declare methods that
	// this path will be valid for
	r.HandleFunc("/hello", handler).Methods("GET")

	// We can then pass our router (after declaring all our routes) to this method
	// (where previously, we were leaving the second argument as nil)
	http.ListenAndServe(":8080", r)
}

// "handler" is our handler function. It has to follow the function signature of a ResponseWriter and Request type
// as the arguments.
func handler(w http.ResponseWriter, r *http.Request) {
	// For this case, we will always pipe "Hello World" into the response writer
	fmt.Fprintf(w, "Hello World!")
}
```
Then run: `go get github.com/gorilla/mux`
And now try to run the go application with: `go run main.go`


**Expected behavior**
> What output or behaviour were you expecting instead?

Expecting to work xD

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

NA

**Comment by ya5u** [comment] 2022-02-25 13:13
@oswinfox  it's not a bug, but a problem with your environment.

Running `go mod init testproject` and `go mod tidy` before `go run main.go` might help the situation.  
[This doc](https://go.dev/ref/mod) may help you to understand Go Modules.

**Comment by oswinfox** [comment] 2022-02-25 13:16
@ya5u yes indeed, I confirm this work after I do the following in my project folder: 

```
go mod init testproject
go mod tidy
```

Thanks for your help!

**Comment by andrew-werdna** [comment] 2022-03-25 02:10
@imjmakki this is not a bug. You need to create a [go module](https://go.dev/blog/using-go-modules) before you can run your sample program _if you are importing and using someone else's code_. 

Just running your freshly finished `main.go` is fine if you are just using the standard library but when you are depending on someone else's code you need to create a module since this is what Go uses for dependency management.

> Starting in Go 1.13, module mode will be the default for all development. 

Meaning you must run 
```
go mod init
go mod tidy
``` 
after creaing your `main.go` that imports other people's code as explained by @ya5u.
Does what I've said make sense? I would suggest reading the article I linked. It helped me understand when I first started out with Go.

**Comment by dewunmirokeeb** [comment] 2022-04-05 03:39
i have this similar problem, my own issue is that i can't install the package with go get, i learnt that go get is no longer supported outside a module  and i should use go install instead. i did as told and my issue still persist, how can i install the package with go install ? ... thanks in advance

**Comment by james-d-elliott** [comment] 2022-04-06 01:51
Can you explain your motivation behind not using a go.mod? I'd suggest  just `go mod init x` where x is an arbitrary name for your module. There is really no disadvantage to this and is not really an issue related to this project.

**Comment by dewunmirokeeb** [comment] 2022-04-07 10:08
i just started learning programming with flutter, in one of the tutorial project i am currently working on, the guy uses go to offer back end service to the app, hence i needed to do the same so as to get along with him, how ever i can't install the package by just typing 'go get github.com/gorilla/mux' in my command line as i get a message saying "go get" is no longer supported to install a package, i should use "go install", and that's where i am stucked... is there any way i can install the package with go install keyword instead of go get.. thanks........... i will appreciate your help so much

**Comment by andrew-werdna** [comment] 2022-04-07 11:30
Actually, for all of you who are doing some sort of "front end development" (mobile, web, it doesn't matter) and have jumped to the conclusion that you now need to build a simple Rest API to provide data to that front end, you can just use [this](https://jsonplaceholder.typicode.com/guide/) free, already existing API.

@dewunmirokeeb 
@imjmakki 

Please, please just run
```
go mod init x
go mod tidy
```
Also, can someone please close this issue as not a bug. 

I am speculating that this problem keeps happening on so many OSS projects because ESL students are confusing the overloaded term "install". People keep thinking they need to run `go install` in order to use a package, and people keep not learning enough Go to know about modules somehow. I'm wondering if there is some way the Go community can increase visibility into Go's module system, so new students don't keep missing it.

**Comment by judeharding** [comment] 2022-05-19 00:53
Yes - -had similar problem as of May 18, 2022.  

Created my directory.
Created my main.go file
Copied the main.go file from above.

Then, in terminal, typed   go mod init nameOfOrojectHoldingMymMainDotGoFile
Then, in terminal, typed   go mod tidy.

**Comment by dolanor** [comment] 2022-05-22 23:24
And what is the problem, exactly?
You've done the right thing. 

Now you should be able to `go get github.com/gorilla/mux` and then use it from your project, and it should just work.

**Comment by amustaque97** [comment] 2022-05-31 10:09
@elithrar we can close this issue. 
Thank You

**Closed** 2022-05-31 11:25 UTC
Labels: bug
