### ISSUE TITLE
Subrouters match the wrong method when more than one matches

### ISSUE THREAD

**Issue by silverweed** [gorilla/mux#300] opened 2017-10-02 10:28 UTC
Introduced by https://github.com/gorilla/mux/pull/288.
Given the following code:

```go
package main

import (
	"fmt"
	"net/http"

	"github.com/gorilla/mux"
)

func main() {
	router := mux.NewRouter()
	get := router.Methods("GET", "HEAD").Subrouter()
	post := router.Methods("POST").Subrouter()

	post.HandleFunc("/some/{thing}", func(rw http.ResponseWriter, req *http.Request) {
		fmt.Fprintln(rw, "post")
	})
	get.HandleFunc("/some/{thing}", func(rw http.ResponseWriter, req *http.Request) {
		fmt.Fprintln(rw, "get")
	})

	http.Handle("/", router)
	http.ListenAndServe(":8888", nil)
}
```

a POST request to /some/thing will always match the `get` subrouter:

```sh
curl localhost:8888/some/thing -X POST # -> get
```

The same happens when there is a subrouter with a "catch-all" route, like 
```go
get.HandleFunc("/{anything}", getAnything)
```
This route will match any valid POST route *without parameters*. 

These behaviours happen no matter the calling order of the `HandleFunc`s.

Commenting [these lines](https://github.com/gorilla/mux/blob/master/route.go#L61-L64) seems to solve the issue, but of course breaks #288

**Comment by leofachini** [comment] 2017-10-08 06:21
I'm facing the same problem as you @silverweed, but with another route setup. (Would you think these might be related? If not, I will open a new issue.)

With the following code:

`func main() {
	r := mux.NewRouter()
	sub := r.PathPrefix("/").Subrouter()

	sub.StrictSlash(true).Path("/test").Methods("GET").HandlerFunc(getFunc)
	sub.StrictSlash(true).Path("/test").Methods("POST").HandlerFunc(postFunc)

	log.Fatal(http.ListenAndServe(":3000", r))
}

func getFunc(w http.ResponseWriter, r *http.Request) {

	fmt.Printf("%+v\n", r.Method)

	json.NewEncoder(w).Encode(r.Method)
}

func postFunc(w http.ResponseWriter, r *http.Request) {

	fmt.Printf("%+v\n", r.Method)

	json.NewEncoder(w).Encode(r.Method)
}
`

A GET to localhost:3000/test will result in:
`GET` :heavy_check_mark:

A GET to localhost:3000/test/ will result in:
`GET` :heavy_check_mark:

A POST to localhost:3000/test will result in:
`POST` :heavy_check_mark:

**A POST to localhost:3000/test/ will result in:**
`GET` :x: (unexpected behavior)

**Comment by stevenh** [comment] 2017-10-19 11:11
This has hit us too, the current 1.5.0 release is totally broken for any users that have Method based routing.

It appears to be fixed in master, but no release has been performed yet which means anyone updating using ^1.x... semantic versioning will end up with broken apps.

Given this there really need to be 1.5.1 release urgently to address this.

**Comment by elithrar** [comment] 2017-10-19 16:27
Pinging @kisielk, because I’m away, but if it’s critical I suggest updating
your dependency manifest to pin against the ref that resolves the bug
(which is what makes pinning useful!).

**Comment by stevenh** [comment] 2017-10-19 21:04
Yes thats exactly what we’ve done but not before it caused an outage for our customers.
So just trying to help protect others from such an outage.

**Comment by roobre** [comment] 2017-11-03 18:23
Maybe I can look into this if any of the affected users add some test cases. I just tweaked this code in #311, so it shouldn't be difficult for me to fix this.

**Comment by elithrar** [comment] 2017-11-04 23:50
Plan:

1. Add more test cases to the library for this - especially around
Subrouters / PathPrefix cases, to see whether we can reproduce internally
w/o user code
2. If #1 identifies issues, fix.

There are already a good number of tests for #1 so these reports are
worrying, but definitely want to fix. I'll earmark some time tomorrow to
tackle #1.

**Comment by roobre** [comment] 2017-11-05 01:03
Maybe I can take a look at the user examples to see if they can be ported to tests. I'll give it a try tomorrow.

**Comment by mtso** [comment] 2017-11-26 00:07
Hi @roobre, are you still working on this? If not, I'd like to take a stab at it.

I think there might be here: https://github.com/gorilla/mux/blob/master/route.go#L84
It's assigning a handler only if `match.Handler` is `nil`, but it's not for an invalid method match.

**Comment by roobre** [comment] 2017-11-26 14:34
I'm quite on hold since reviewers are on vacation :(

I planned to get on this when my PR (#294) gets resolved, but if you want to look at it, be my guest :3

**Comment by kisielk** [comment] 2017-11-28 23:23
@silverweed @leofachini @stevenh @roobre can you check if the PR today fixed this for you?

**Comment by silverweed** [comment] 2017-11-29 14:07
@kisielk Looks like it's working well :)
Thank you!

**Comment by elithrar** [comment] 2017-11-29 15:32
Closing this out.

**Closed by elithrar** 2017-11-29 15:32 UTC
Labels: bug, helpwanted

**Comment by etrapani** [comment] 2020-07-12 00:12
I remove the strictSlash and everything work
