### ISSUE TITLE
StrictSlash empty body issue

### ISSUE THREAD

**Issue by EmmanuelVlad** [gorilla/mux#369] opened 2018-04-30 16:27 UTC
**What version of Go are you running?** go1.9.4 darwin/amd64

**What version of gorilla/mux are you at?** b57cb1605fd11ba2ecfa7f68992b4b9cc791934d

**Describe your problem**
StrictSlash works partially, it enters in the route Handler but the body is empty.

Results:
GET /test BODY  { "something": "something" }
it returns "Nice", that means the body is not empty

GET /test/ BODY  { "something": "something" }
it returns nothing, you can see error EOF in the logs

Try the code below 

**Paste a minimal, runnable, reproduction of your issue below**
```golang
package main

import (
	"encoding/binary"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strconv"
	"strings"

	"github.com/gorilla/mux"
)

func main() {
	router := mux.NewRouter()

	router.StrictSlash(true)

	router.HandleFunc("/test", func(w http.ResponseWriter, r *http.Request) {
		var body map[string]interface{}

		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			fmt.Println(err)
			return
		}
		fmt.Fprintf(w, "Nice")
	})
	http.ListenAndServe(":"+port, router)

}
```

Have a good day! :)

**Comment by elithrar** [comment] 2018-04-30 20:53
How are you making requests? e.g. another Go program?

**Comment by elithrar** [comment] 2018-04-30 20:59
Unable to reproduce - slightly modified to log requests:
```go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"

	"github.com/gorilla/mux"
)

func LogRequest(h http.Handler) http.Handler {
	fn := func(w http.ResponseWriter, r *http.Request) {
		log.Printf("method: %s | url: %s", r.Method, r.URL.String())
		h.ServeHTTP(w, r)
	}

	return http.HandlerFunc(fn)
}

func main() {
	router := mux.NewRouter()

	router.StrictSlash(true)
	router.Use(LogRequest)

	router.HandleFunc("/test", func(w http.ResponseWriter, r *http.Request) {
		var body map[string]interface{}

		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			http.Error(w, err.Error(), 400)
			return
		}
		fmt.Fprintf(w, "body: %s\n", body)
	})

	log.Fatal(http.ListenAndServe("localhost:8000", router))
}
```

Request:
```sh
➜  ~/Desktop  go run body.go
2018/04/30 13:58:11 method: POST | url: /test
```
Output:
```sh
➜  ~/Desktop  curl -X POST localhost:8000/test --data '{"hello":"world"}'
body: map[hello:world]
```
Note the `body: map[hello:world]` in the response body returned by curl, as expected.

**Comment by kisielk** [comment] 2018-04-30 21:29
I think the difference is that @EmmanuelVlad is using GET instead of POST. Most likely curl doesn't preserve the body when following the redirect.

**Comment by elithrar** [comment] 2018-04-30 22:18
Correct, it does not. A POST request that receives a HTTP 301 / 302 will be followed up as a GET, which follows HTTP semantics.

A HTTP status of 307 would instruct the client to follow up with a POST and preserve the body.

**Comment by elithrar** [comment] 2018-04-30 22:44
Here's middleware that you can use to re-write 301 && 302 to 307 && 308 

```go
type ResponseWriter struct {
	http.ResponseWriter
	status               int
	retainRedirectBodies bool
	wroteHeader          bool
}

func NewResponseWriter(w http.ResponseWriter, retainRedirectBodies bool) *ResponseWriter {
	return &ResponseWriter{ResponseWriter: w, retainRedirectBodies: retainRedirectBodies}
}

func (w *ResponseWriter) Status() int {
	return w.status
}

func (w *ResponseWriter) Write(p []byte) (n int, err error) {
	if !w.wroteHeader {
		w.WriteHeader(http.StatusOK)
	}

	return w.ResponseWriter.Write(p)
}

func (w *ResponseWriter) WriteHeader(code int) {
	if w.retainRedirectBodies {
		if code == http.StatusPermanentRedirect {
			code = 307
		} else if code == http.StatusPermanentRedirect {
			code = 308
		}
	}

	w.ResponseWriter.WriteHeader(code)
	if w.wroteHeader {
		return
	}
	w.status = code
	w.wroteHeader = true
}

func RetainBodyOnRedirect(h http.Handler) http.Handler {
	fn := func(w http.ResponseWriter, r *http.Request) {
		wr := NewResponseWriter(w, true)
		h.ServeHTTP(wr, r)
	}

	return http.HandlerFunc(fn)
}
```

Then just add it to your middleware stack:

```go
	router := mux.NewRouter()

	router.StrictSlash(true)
	router.Use(RetainBodyOnRedirect)
```

Hope that helps. Closing this, but re-open if you have any issues or questions!

**Closed by elithrar** 2018-04-30 22:44 UTC
Labels: question

**Comment by EmmanuelVlad** [comment] 2018-05-02 10:00
Hey, first of all thanks for the help
I had to change
```go
case http.StatusPermanentRedirect:
	code = 308
case http.StatusTemporaryRedirect:
	code = 307
```
to
```go
case http.StatusFound:
	code = 308
case http.StatusMovedPermanently:
	code = 307
```
in order to redirect from 301/302 to 307/308

Thanks again :)

**Comment by EmmanuelVlad** [comment] 2018-05-02 12:52
Another problem I found:

ANY METHOD `/test//` redirects to `/test/` (loses the body) then redirects (301) to `/test`
